name: Syntax Checker

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  analyze_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch changed files
        id: changed_files
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \

      - name: Check changed files
        run: node .scripts/check.js ${{ steps.changed_files.outputs.files }}
