name: Syntax Checker

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  analyze_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch changed files
        id: changed_files
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN  }}" \
            "https://api.github.com/repos/${{ github.repository  }}/pulls/${{ github.event.pull_request.number  }}/files")
          echo "::set-output name=files::$(echo $response | jq -r '.[].filename')"

      - name: Check changed files
        run: node .scripts/check.js ${{ steps.changed_files.outputs.files }}
